### ISSUE TITLE
Link color on landing page is not common

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#147]
Some are green, some aren't.

**Comment by AdrieanKhisbe** [comment]
Looks like a *feature, not a bug*: 

Visited vs non visited:

```css
a:visited {
    color: #379199;
}
a {
    color: #f07057;
}
```
