### ISSUE TITLE
CSS is incorrectly specifying 'monospaced'

### ISSUE THREAD

**Issue by wezm** [senecajs/senecajs.org#301]
The CSS rule for monospaced text on the site is:

```css
pre, code {
    font-family: Menlo, Monaco, Consolas, monospaced;
}
```

On my Linux machine I don't have Menlo, Monace or Consolas and the last family name should be the generic font family name [monospace](http://mdn.beonex.com/en/CSS/font-family.html#Values). As a result all the text is falling back on the default serif browser font:

![screenshot from 2017-05-15 09-19-23](https://cloud.githubusercontent.com/assets/21787/26038662/b12adb9e-3950-11e7-9f82-18a92c300ca0.png)
